Use cached group counts
kodi-pvr/pvr.nextpvr pull request #205
Opened 2021-12-30 15:57 UTC by emveepee

Nexus can poll group counts frequently.  Use the internal counts rather then unnecessarily calling the backend.

2021-12-30 16:08 UTC, phunkyfish requested changes

2021-12-30 16:08 UTC, phunkyfish commented on pvr.nextpvr/addon.xml.in
> +  name="NextPVR PVR Client"344
typo

2021-12-30 16:28 UTC, phunkyfish approved these changes

2021-12-30 16:35 UTC, emveepee commented on pvr.nextpvr/addon.xml.in
> +  name="NextPVR PVR Client"344
Thanks fixed.

2021-12-30 16:49 UTC, emveepee commented
@phunkyfish @AlwinEsch  do these buiild failures have anything to do with PR #204  or did my original faulty addon.xml.in cause an issue in the build system?

2021-12-30 17:21 UTC, phunkyfish commented
Yes, they are related to the API change. Once the PRs get merged and released they should start to pass.

2022-01-02 15:12 UTC, emveepee commented
@phunkyfish how do I resolve this?  I am not getting conflicts on my source and I can't see where to change the head of the PR

2022-01-02 15:55 UTC, phunkyfish commented
> @phunkyfish how do I resolve this? I am not getting conflicts on my source and I can't see where to change the head of the PR

Drop the second commit, then rebase on the Nexus branch. Then update the version number and amend the original commit.

2022-01-02 16:16 UTC, emveepee commented
@phunkyfish thanks a lot,  I was rebasing but I wasn't thinking to do it against Nexus.

@sub3 can you tag and merge this, they might as well go together in the nightly.

2022-01-02 21:19 UTC, merged