Trigger channel list updates
kodi-pvr/pvr.nextpvr pull request #280
Opened 2024-12-24 19:20 UTC by emveepee

Store a hash of the XML channel list and if the hash changes after an EPG update trigger Kodi to reload the channel list and channel groups.  Use cache to remove obsolete channel icons. Add error checking to channel cache logic introduced in Piers.

2025-01-06 10:18 UTC, phunkyfish requested changes

2025-01-06 10:18 UTC, phunkyfish commented on src/EPG.cpp
> +  std::lock_guard<std::recursive_mutex> unlock(m_channels.m_channelMutex);
Just put the protected line in a block instead. You should never need to unlock:

```
  {
    std::lock_guard<std::recursive_mutex> lock(m_channels.m_channelMutex);
    channelDetail = m_channels.m_channelDetails[channelUid];
  }
```

2025-01-06 13:39 UTC, emveepee commented on src/EPG.cpp
> +  std::lock_guard<std::recursive_mutex> unlock(m_channels.m_channelMutex);
Thanks I didn't know that was prefered

2025-01-15 07:42 UTC, phunkyfish approved these changes

2025-01-18 02:12 UTC, merged